config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :expenses_sheet, only: [:index, :show, :create, :destroy, :edit, :update] do
    get 'fullcalendar'
    resources :expenses, only: [:create, :destroy] do
      get 'claim' #maybe unnecesary anidation, unless want to change expense to another sheet
    end
    resources :asociations, only: [:create]
  end
  resources :expenses, only: [:edit, :update]
  devise_for :users, controllers: {
    sessions: 'users/sessions', # acive_admin needs this
    registrations: 'users/registrations'
  }
  get 'landing/index'
  #root to: "expenses_sheet#index"
  root to: "landing#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if alert.present? %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= landing_index_path %>">Landing</a>
  <a class="navbar-brand" href="<%= expenses_sheet_index_path %>">Inicio</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      
        <% if !user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Registrarse',  new_user_registration_path, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link"><%= current_user.show_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %>
          </li>
        <% end %>
        
    </ul>
  </div>
</nav>