config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :expenses_sheet, only: [:index, :show, :create, :destroy, :edit, :update] do
    get 'fullcalendar'
    resources :expenses, only: [:create, :destroy] do
      get 'claim' #maybe unnecesary anidation, unless want to change expense to another sheet
    end
    resources :asociations, only: [:create]
  end
  resources :expenses, only: [:edit, :update]
  devise_for :users, controllers: {
    sessions: 'users/sessions', # acive_admin needs this
    registrations: 'users/registrations'
  }
  get 'landing/index'
  #root to: "expenses_sheet#index"
  root to: "landing#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expenses_sheet.rb
class ExpensesSheet < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :expenses, dependent: :destroy
  has_many :asociations, dependent: :destroy
  has_many :users, through: :asociations #and_belongs_to?? TODO
  has_many :categories, through: :expenses

  validates :name, presence: { message: "must be given please" }

  def asociationLevel
    self.asociations.count()
  end
  def totalUnpaid
    self.expenses.where(user: nil).pluck("amount").sum()
  end
  def expensesCountToClaim
    self.expenses.where(user: nil).count()
  end
  def totalSpent
    self.expenses.pluck("amount").sum()
  end
  def userSpent(user)
    self.expenses.where(user: user).pluck("amount").sum()
  end

  def userBalance(user)
    # gaste 50 somos 2 y el otro puso:
    # 0: 50 - (50/2) = +25
    # 50: 50 - (100/2) = 0
    # 100: 50 - (150/2) = -25

    # WARNING this trigers 3 queries
    puts '!!userBalance trigers 3 queries'
    userSpent(user) - (totalSpent / asociationLevel.to_f)
  end

  def userSummary(user, asociationLevelTaken, userSpentTaken)
    summary = Hash.new
    summary[:totalSpent] = totalSpent
    summary[:userBalance] = userSpentTaken - (summary[:totalSpent] / asociationLevelTaken.to_f)
    summary
  end

  def is_user_asociated(user)
    self.users.where(id: user.id).present?  
  end
end

app/controllers/expenses_sheet_controller.rb
class ExpensesSheetController < ApplicationController

  before_action :set_expensesSheet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  authorize_resource
  def index
    @expensesSheets = current_user.expensesSheets
    @newExpensesSheet = ExpensesSheet.new
  end

  def fullcalendar
    @expensesSheet = ExpensesSheet.find(params[:expenses_sheet_id])
    @expenses = @expensesSheet.expenses
    @expenses_calendar = []
    @expenses.each do |e|
      @expenses_calendar << {"title"=>"$#{e.amount} #{e.name}", "start"=>e.start, "url"=>edit_expense_path(e) }
    end

  end

  def show
    authorize! :read, @expensesSheet
    @expenses = @expensesSheet.expenses.order("created_at DESC")
    # graficDoughnut
    @expenses_by_category = Hash.new
    @expenses.preload(:category).each do |e|
      # SELECT category, sum(amount) FROM @expenses GROUP BY Category
      if @expenses_by_category[e.category.name] == nil
        @expenses_by_category[e.category.name] = e.amount
      else
        @expenses_by_category[e.category.name] += e.amount
      end
    end
    # graficPie
    @expenses_by_asociation = Hash.new
    @expensesSheet.asociations.preload(:user).each do |a|
      @expenses_by_asociation[a.user.show_name] = @expensesSheet.userSpent(a.user)
    end 
    # expenses form
    @newExpense = Expense.new
    @categories = Category.all
    # asociation form
    @newAsociation = Asociation.new
    respond_to do |format|
      format.html
      format.csv { send_data @expenses.to_csv, filename: "gastos-#{@expensesSheet.name}-#{Date.today}.csv" }
    end
  end

  def edit
    # not void, remember set_history => @expensesSheet = ExpensesSheet.find(params[:id])
  end

  def update
    @expensesSheet.name = params[:expenses_sheet][:name]

    respond_to do |format|
      if @expensesSheet.save
        format.html { redirect_to expenses_sheet_index_path, notice: 'expensesSheet name was successfully changed.' }
        format.json { render :show, status: :created, location: @expensesSheet }
      else
        format.html { redirect_to expenses_sheet_index_path, alert: "newExpensesSheet name was not changed. #{@expensesSheet.errors.full_messages}" }
        format.json { render json: @expensesSheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @newExpensesSheet = current_user.expensesSheets.build(owner: current_user, name: params[:expenses_sheet][:name])

    respond_to do |format|
      if @newExpensesSheet.save
        Asociation.create!(
          user: current_user,
          expensesSheet: @newExpensesSheet
        )
        format.html { redirect_to expenses_sheet_index_path, notice: 'newExpensesSheet was successfully created.' }
        format.json { render :show, status: :created, location: @newExpensesSheet }
      else   
        format.html { redirect_to expenses_sheet_index_path, alert: "newExpensesSheet was not created. #{@newExpensesSheet.errors.full_messages}" }
        format.json { render json: @newExpensesSheet.errors, status: :unprocessable_entity } 
      end
    end
  end

  def destroy
    authorize! :destroy, @expensesSheet
    @expensesSheet.destroy
    respond_to do |format|
      format.html { redirect_to expenses_sheet_index_path, notice: 'ExpensesSheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_expensesSheet
    @expensesSheet = ExpensesSheet.find(params[:id])
  end
end

app/helpers/expenses_sheet_helper.rb
module ExpensesSheetHelper
end

app/views/expenses_sheet/_balanceTable.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">userSpent</th>
      <th scope="col">userBalance</th>
      <th scope="col">totalUnpaid</th>
      <th scope="col">#asociation</th>
      <th scope="col">owner</th>
    </tr>
  </thead>
    <tr>
      <td><%= @expensesSheet.name %></td>
      <td><%= number_to_currency(@expensesSheet.userSpent(current_user)) %></td>
      <td><%= number_to_currency(@expensesSheet.userBalance(current_user)) %></td>
      <td><%= number_to_currency(@expensesSheet.totalUnpaid) %></td>
      <td><%= @expensesSheet.asociationLevel %></td>
      <td><%= @expensesSheet.owner.show_name %></td>
    </tr> 
  </tbody>
</table>

app/views/expenses_sheet/_expensesTable.html.erb
<!-- used in expenses_sheet/show -->
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Amount</th>
      <th scope="col">Category</th>
      <th scope="col">owner</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= render 'expenses/form' %>
    </tr>
  <% @expenses.each_with_index do |expense,index| %>
    <tr>
        <%= render expense %>      
    </tr>    
  <% end %>
    <tr>
      <th scope="row"><%="Total"%></th>
      <td><%= @expensesSheet.expenses.count() %></td>
      <td><%= number_to_currency(@expensesSheet.totalSpent, strip_insignificant_zeros: true) %></td>
      <td></td>      
      <td></td>
    </tr>
  </tbody>
</table>

app/views/expenses_sheet/_form.html.erb
<%= form_with model: @newExpensesSheet, url: expenses_sheet_index_path, method: :post, local: true do |f| %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nombre para la nueva hoja de gastos</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.text_field :name %></td>
        <td><%= f.submit "Crear", class: "btn btn-primary" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/expenses_sheet/_graficBar.html.erb
<canvas id="myBarChart" width="400" height="400"></canvas>
<script>
  var ctx = document.getElementById("myBarChart");
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: <%=@expenses.map { |e| e.name }.to_json.html_safe%>,
          datasets: [{
              label: '<%=@expensesSheet.name.upcase%>',
              data: <%=@expenses.map { |e| e.amount.to_i }%>,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });
</script>

app/views/expenses_sheet/_graficDoughnut.html.erb
<canvas id="myDoughnutChart" width="400" height="400"></canvas>
<script>
  var ctx = document.getElementById("myDoughnutChart");
  var myChart = new Chart(ctx, {
      type: 'doughnut',
      data: {
          labels: <%=@expenses_by_category.keys.to_json.html_safe%>,
          datasets: [{
              data: <%=@expenses_by_category.values.to_json.html_safe%>,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(99, 255, 132, 0.2)',
                  'rgba(99, 132, 255, 0.2)',

                  'rgba(255, 99, 132, 0.4)',
                  'rgba(99, 255, 132, 0.4)',
                  'rgba(99, 132, 255, 0.4)',

                  'rgba(255, 99, 132, 0.6)',
                  'rgba(99, 255, 132, 0.6)',
                  'rgba(99, 132, 255, 0.6)',

                  'rgba(255, 99, 132, 0.8)',
                  'rgba(99, 255, 132, 0.8)',
                  'rgba(99, 132, 255, 0.8)',
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(99,255,132,1)',
                  'rgba(99, 132, 255, 1)',
                  'rgba(255,99,132,1)',
                  'rgba(99,255,132,1)',
                  'rgba(99, 132, 255, 1)',
                  'rgba(255,99,132,1)',
                  'rgba(99,255,132,1)',
                  'rgba(99, 132, 255, 1)',
                  'rgba(255,99,132,1)',
                  'rgba(99,255,132,1)',
                  'rgba(99, 132, 255, 1)',
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });
</script>

app/views/expenses_sheet/_graficPie.html.erb
<canvas id="myPieChart" width="400" height="400"></canvas>
<script>
  var ctx = document.getElementById("myPieChart");
  var myChart = new Chart(ctx, {
      type: 'pie',
      data: {
          labels: <%=@expensesSheet.asociations.map { |a| a.user.email }.to_json.html_safe%>,
          datasets: [{
              data: <%=@expensesSheet.asociations.map { |a| @expensesSheet.userSpent(a.user) }%>,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(99, 255, 132, 0.2)',
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(99,255,132,1)',
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });
</script>

app/views/expenses_sheet/_newAsociationsForm.html.erb
<% if current_user == @expensesSheet.owner %>
  <%= form_with model: @newAsociation, url: expenses_sheet_asociations_path(@expensesSheet), method: :post, local: true do |f| %>
    <div class="field">
      Añadir colaborador por email
      <%= f.email_field :email, autocomplete: "email", style: "width:90%" %>
      <%= f.submit "Añadir", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/expenses_sheet/_sidebar.html.erb
<nav id="sidebar">
    <div class="sidebar-header">
        <a class="navbar-brand" href="<%= root_path %>"><h3>Inicio</h3></a>
        <a class="nav-link"><%= current_user.email %></a>
        <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link' %>
    </div>

    <ul class="list-unstyled components">
        <li>
          <a id="showTableButton" onclick="$('.hideable').hide(); $('#expensesTable').show();">
            <%= @expensesSheet.name %>
          </a>
        </li>
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Resumen:</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">userSpent: <%= number_to_currency(@expensesSheet.userSpent(current_user)) %></a>
                </li>
                <li>
                    <a href="#">userBalance: <%= number_to_currency(@expensesSheet.userBalance(current_user)) %></a>
                </li>
                <li>
                    <a href="#">totalUnpaid: <%= number_to_currency(@expensesSheet.totalUnpaid) %></a>
                </li>
                <li>
                    <a href="#">owner: <%= @expensesSheet.owner.email %></a>
                </li>
            </ul>
        </li>
        <li class="active">
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">AsociationLevel: <%= @expensesSheet.asociationLevel %></a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <% @expensesSheet.asociations.each do |asociation| %>
                  <li>
                    <a href="#">
                        <%= asociation.user.email %>
                    </a>
                  </li>
                <% end %>
                <li>
                    <% if current_user == @expensesSheet.owner %>
                        <%= render 'asociations/form' %>
                    <% end %>
                </li>
            </ul>
        </li>
        <li class="active">
            <a href="#pageGraphs" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Graphs</a>
            <ul class="collapse list-unstyled" id="pageGraphs">
                <li>
                    <a id="showBarButton" onclick="$('.hideable').hide(); $('#graficBar').show();">Bar</a>
                </li>
                <li>
                    <a id="showPieButton" onclick="$('.hideable').hide(); $('#graficPie').show();">Pie</a>
                </li>
                <li>
                    <a id="showDoughnutButton" onclick="$('.hideable').hide(); $('#graficDoughnut').show();">Doughnut</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<script>
    function hashCode(str) { // java String#hashCode
        var hash = 0;
        for (var i = 0; i < str.length; i++) {
           hash = str.charCodeAt(i) + ((hash << 5) - hash);
        }
        return hash;
    } 

    function intToRGB(i){
        var c = (i & 0x00FFFFFF).toString(16).toUpperCase();
        return "00000".substring(0, 6 - c.length) + c;
    }

    var color = intToRGB(hashCode("<%= @expensesSheet.name %>"));
    document.getElementById("sidebar").style.backgroundColor = "#"+color;
</script>

app/views/expenses_sheet/edit.html.erb
  <h1>ExpensesSheet#edit</h1>
  <%= link_to "#{@expensesSheet.name}", @sheet, 'data-turbolinks': false %>

<%= form_with model: @expensesSheet, url: expenses_sheet_path, method: :patch, local: true do |f| %>
  <p><%= f.text_field :name %></p>
  <p><%= f.submit "Editar", class: "btn btn-primary" %></p>
<% end %>
<%= link_to 'Volver', expenses_sheet_index_path, class: "btn btn-info" %></p>

app/views/expenses_sheet/fullcalendar.html.erb
<div  style="float: left;">
  <%= link_to "Volver a hojaDeGasto", expenses_sheet_url(@expensesSheet), class: "btn btn-primary" %>
</div>
<h1>
  Calendario de 
  <%= link_to "#{@expensesSheet.name}", @expensesSheet, 'data-turbolinks': false %>
</h1>
<div id='calendar'></div>

<script>
  document.addEventListener("turbolinks:before-cache", function() {
    $('#calendar').fullCalendar('destroy');
  })
  document.addEventListener("turbolinks:load", function() {
    $('#calendar').fullCalendar({
      header: {
        left: 'month,listWeek',
        center: 'title',
        right: 'prevYear,prev,prevWeek,next,nextYear'
      },
      firstDay: 1,
      events: <%= raw @expenses_calendar.to_json() %>
    });
  })
</script>

app/views/expenses_sheet/index.html.erb
<!-- comments container -->
<div class="comment_block" style="margin-top: 10px">
  <h1>Inicio</h1>

   <!-- new comment -->
   <div class="new_comment">

    <!-- build comment -->
    <ul class="user_comment">
      <!-- current #{user} avatar -->
      <div class="user_avatar">
        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/BillSKenney/73.jpg">
      </div><!-- the comment body --><div class="comment_body">
          Hola <%= current_user.show_name%>!!
          <br>
          Tiene <%= @expensesSheets.count() %> hojasDeGasto,
          en donde ha gastado <%= number_to_currency(current_user.userSpent, strip_insignificant_zeros: true) %>
          <br>
          <%= current_user.userBalance < 0 ? 'SIENTO INFORMARLE que' : 'FELICIDADES' %>
          su balance es <%= number_to_currency(current_user.userBalance, strip_insignificant_zeros: true, precision: 0) %></td>
      </div>
      <!-- comments toolbar -->
      <div class="comment_toolbar">
        <!-- inc. date and time -->
        <div class="comment_details">
          <ul>
            <li><i class="fa fa-pencil"></i> <span class="user"><%= current_user.name%></span></li>
            <li><i class="fa fa-clock-o"></i> registrado hace <%=time_ago_in_words(current_user.created_at)%></li>
            <li><i class="fa fa-calendar"></i> con fecha <%= current_user.created_at.to_date %> </li>
          </ul>
        </div><!-- inc. share/reply and love -->
      </div>
      <!-- start user replies -->
      <% @expensesSheets.each do |expensesSheet| %>
      <!-- render expenseSheet not working :( -->
      
          <%= render expensesSheet %>     
      <!-- render expenseSheet not working :( -->
      <% end %>
    </ul>
  </div>

  <!-- used by #{user} to create a new comment -->
  <div class="create_new_comment">
    <div class="input_comment">
      <div class="title">
        Crear una nueva hojaDeGastos
      </div>
      <%= render 'expenses_sheet/form' %>
    </div>
  </div>
</div>

app/views/expenses_sheet/show.html.erb
<div class="wrapper">
  <!-- Sidebar -->
  <%= render 'expenses_sheet/show/sidebar' %>
  <!-- Container -->
  <div class="container">
    <div class="row">
      <div class="col-sm-12 hideable" id="expensesTable">
        <%= render 'shared/alerts'%>
        <%= render 'expenses/block_index' %>
      </div>
      <div class="col-sm-8 hideable" id="graficBar" style="display: none">
        <%= render 'expenses_sheet/show/grafic/graficBar' %>
      </div>
      <div class="col-sm-8 hideable" id="graficPie" style="display: none">
        <%= render 'expenses_sheet/show/grafic/graficPie' %>
      </div>
      <div class="col-sm-8 hideable" id="graficDoughnut" style="display: none">
        <%= render 'expenses_sheet/show/grafic/graficDoughnut' %>
      </div>     
    </div>
  </div>    
</div>