config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :expenses_sheet, only: [:index, :show, :create, :destroy, :edit, :update] do
    get 'fullcalendar'
    resources :expenses, only: [:create, :destroy] do
      get 'claim' #maybe unnecesary anidation, unless want to change expense to another sheet
    end
    resources :asociations, only: [:create]
  end
  resources :expenses, only: [:edit, :update]
  devise_for :users, controllers: {
    sessions: 'users/sessions', # acive_admin needs this
    registrations: 'users/registrations'
  }
  get 'landing/index'
  #root to: "expenses_sheet#index"
  root to: "landing#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  
  def create
    @newExpense = Expense.new()
    @newExpense.amount = params[:expense][:amount].scan(/[.0-9]/).join().to_i
    @newExpense.name = params[:expense][:name]
    @newExpense.expenses_sheet_id = params[:expenses_sheet_id]
    @newExpense.category_id = params[:category_id]
    if Expense.start_secure? params[:expense][:start]
      @newExpense.start = params[:expense][:start]
    else
      @newExpense.start = Time.now()
    end
    @newExpense.user = current_user if params[:expense][:owner] == '1'
      
    authorize! :create, @newExpense
    respond_to do |format|
      if @newExpense.save
        format.html { redirect_to expenses_sheet_url(@newExpense.expensesSheet), notice: 'newExpense was successfully created.' }
        format.json { render :show, status: :created, location: @newExpense }
      else
        format.html { redirect_to expenses_sheet_url(@newExpense.expensesSheet), notice: "newExpense was not created.#{@newExpense.errors.full_messages}" }
        format.json { render json: @newExpense.errors, status: :unprocessable_entity }
      end
    end
  end

  def claim
    @expense = Expense.find(params[:expense_id])
    authorize! :claim, @expense
    @expense.user = current_user
    respond_to do |format|
      if @expense.save
        format.html { redirect_to expenses_sheet_url(@expense.expensesSheet), notice: 'expense was successfully claimed.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { redirect_to expenses_sheet_url(@expense.expensesSheet), notice: "expense was not created.#{@expense.errors.full_messages}" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    authorize! :destroy, @expense
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_sheet_url(params[:expenses_sheet_id]), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @expense = Expense.find(params[:id])
    authorize! :edit, @expense
    @categories = Category.all
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.amount = params[:expense][:amount].scan(/[.0-9]/).join().to_i
    @expense.name = params[:expense][:name]
    @expense.category_id = params[:category_id]
    @expense.start = params[:expense][:start] if Expense.start_secure? params[:expense][:start]
    @expense.user = current_user if params[:expense][:owner] == '1'
      
    authorize! :update, @expense
    respond_to do |format|
      if @expense.save
        format.html { redirect_to expenses_sheet_url(@expense.expensesSheet), notice: 'expense was successfully updated.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { redirect_to expenses_sheet_url(@expense.expensesSheet), notice: "expense was not updated.#{@expense.errors.messages}" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :name, :owner)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_block_index.html.erb
<!-- comments container -->
<div class="comment_block">
  <!-- used by #{user} to create a new comment -->
  <div class="create_new_comment">
    <div class="input_comment">
      <a href="#addExpense" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">    
        <div class="title">
          Añadir un nuevo gasto
        </div>
      </a>
      <ul class="collapse list-unstyled" id="addExpense">
        <%= render 'expenses/form' %>
      </ul>
    </div>
   </div>

   <!-- new comment -->
   <div class="new_comment">

    <!-- build comment -->
    <ul class="user_comment">
      <!-- current #{user} avatar -->
      <div class="user_avatar">
        <img src="<%=asset_path @expensesSheet.owner.show_avatar%>">
        <%= @expensesSheet.owner.show_name %>
      </div><!-- the comment body --><div class="comment_body">
          Hola <%= current_user.show_name%>!!
           <%= "Tenemos gastos planeados por un valor de: #{number_to_currency(@expensesSheet.totalUnpaid)}" if @expensesSheet.totalUnpaid > 0 %>
          <br>
          <% @userSpent = @expensesSheet.userSpent(current_user) %>
          En esta hojaDeGastos ha gastado <%= number_to_currency(@userSpent, precision: 0) %>;
          <% @asociationLevel = @expensesSheet.asociationLevel %> 
          <% if @asociationLevel > 1 %>
            <% @summary = @expensesSheet.userSummary(current_user, @asociationLevel, @userSpent) %>
            y entre los <%= @asociationLevel %>
            hemos gastado <%= number_to_currency(@summary[:totalSpent], precision: 0) %>,
            <br>
            <%= @summary[:userBalance] < 0 ? 'SIENTO INFORMARLE que' : 'FELICIDADES' %>
            su balance es <%= number_to_currency(@summary[:userBalance], precision: 0) %>
          <% else %>
            esta hojaDeGastos no esta compartida.         
          <% end %>
      </div>
      <!-- comments toolbar -->
      <div class="comment_toolbar">
        <!-- inc. date and time -->
        <div class="comment_details">
          <ul>
            <li><i class="fa fa-pencil"></i> <span class="user"><%= @expensesSheet.name%></span></li>
            <li><i class="fa fa-clock-o"></i> creada hace <%=time_ago_in_words(@expensesSheet.created_at)%></li>
            <li><i class="fa fa-calendar"></i> con fecha <%= @expensesSheet.created_at.to_date %> </li>
          </ul>
        </div><!-- inc. share/reply and love -->
      </div>
      <!-- start user replies -->
      <% @expenses.preload(:user).preload(:category).each_with_index do |expense,index| %>
      <li>
          <%= render expense %>    
      </li> 
      <% end %>
    </ul>
  <a class="btn btn-info text-white" href="<%= @expensesSheet.id %>.csv">Obtener CSV para exportar a Excel</a>
  </div>
</div>

app/views/expenses/_expense.html.erb
<!-- current #{user} avatar -->
<div class="user_avatar">
  <% if expense.user.present? %>
    <img src="<%=asset_path expense.user.show_avatar%>">
    <%= expense.user.show_name %>
  <% else %>
    <%= link_to 'Asumir',expenses_sheet_expense_claim_path(@expensesSheet, expense), class: "btn btn-primary" %>
  <% end %>
</div><!-- the comment body --><div class="comment_body">
    <div class="replied_to">
      <p>
        <span class="user"> <%= expense.show_name  %>:</span>
        <%= number_to_currency(expense.amount, strip_insignificant_zeros: true) %>
      </p>
    </div>
    <%= expense.category.try(:name) %>
    <%= link_to 'Editar', edit_expense_path(expense), class: "btn btn-success btn-sm", 'data-turbolinks': false  %> 
    <%= link_to 'x', expenses_sheet_expense_path(@expensesSheet, expense), method: :delete, data: { confirm: '¿Estas seguro de borrarlo?' }, class: "btn btn-danger btn-sm" %>
</div>

<!-- comments toolbar -->
<div class="comment_toolbar">
  <!-- inc. date and time -->
  <div class="comment_details">
    <ul>
      <li><i class="fa fa-calendar"></i> <%= expense.try(:start) %> </li>
    </ul>
  </div><!-- inc. share/reply and love --><div class="comment_tools">
    <ul>
      <li><i class="fa fa-share-alt">
        <!-- link to show -->
      </i></li>
    </ul>
  </div>
</div>

app/views/expenses/_form.html.erb
<!-- used in expenses/_block_index -->
<%= form_with model: @newExpense, url: expenses_sheet_expenses_path(@expensesSheet, @newExpense), method: :post, local: true do |f| %>

<div class="container-fluid total expenses-container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-md-10">
      <div class="card">
        <div class="card-body">
          <div class="container-fluid">
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :nombre %><br />
                  <%= f.text_field :name %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :cuantia %><br />
                  <%= f.text_field :amount, data: {prefix:"$", thousands: ",", precision: 0}%>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :categoria %><br />
                  <%=
                    select_tag(
                      :category_id,
                      options_from_collection_for_select(@categories.order(:name), :id, :name, @newExpense.category_id)
                    )
                  %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :dueño %><br />
                  <%= f.check_box :owner, {checked: true} %> desmarcar para planear a futuro      
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :fecha %><br />
                  <%= f.text_field :start, class: "datepicker", style: "width: 12rem" %>
                </div>
              </div>
              <div class="col">
                <div class="actions">
                  <%= f.submit "Crear", class:"btn btn-primary" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>

<script>
  $('#expense_amount').maskMoney();
</script>

<script>
  var datepicker = $('.datepicker').datetimepicker(
          { 
            format: 'YYYY/MM/DD',
            icons:
            {
              time: 'fa fa-clock-o',
              date: 'fa fa-calendar',
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down',
              previous: 'fa fa-chevron-left',
              next: 'fa fa-chevron-right',
              today: 'fa fa-calendar-check-o',
              clear: 'fa fa-trash-o',
              close: 'fa fa-close'
            }
          }
        );
  datepicker.css({
    width: '10rem'
  });
</script>

app/views/expenses/edit.html.erb
<h1>Editando  <%= @expense.show_name %> </h1>
<%= form_with model: @expense, url: expense_path(@expense), method: :patch, local: true do |f| %>
<div class="container-fluid total expenses-container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-md-10">
      <div class="card">
        <div class="card-body">
          <div class="container-fluid" style="background-color: moccasin">
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :nombre %><br />
                  <%= f.text_field :name %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :cuantia %><br />
                  <%= f.text_field :amount, data: {prefix:"$", thousands: ",", precision: 0}%>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :categoria %><br />
                  <%=
                    select_tag(
                      :category_id,
                      options_from_collection_for_select(@categories.order(:name), :id, :name, @expense.category_id)
                    )
                  %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <%= f.label :dueño %><br />
                  <%= f.check_box :owner, {checked: false} %> marcar para tomar el gasto      
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <%= f.label :fecha %><br />
                  <%= f.text_field :start, class: "datepicker", style: "width: 12rem" %>
                </div>
              </div>
              <div class="col">
                <div class="actions">
                  <%= f.submit "Guardar", class:"btn btn-primary" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to "Volver a hojaDeGasto", expenses_sheet_url(@expense.expensesSheet), class: "btn btn-success" %>
<% end %>

<script>
  $('#expense_amount').maskMoney();
</script>

<script>
  var datepicker = $('.datepicker').datetimepicker(
          { format: 'YYYY/MM/DD',
            icons:
            {
              time: 'fa fa-clock-o',
              date: 'fa fa-calendar',
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down',
              previous: 'fa fa-chevron-left',
              next: 'fa fa-chevron-right',
              today: 'fa fa-calendar-check-o',
              clear: 'fa fa-trash-o',
              close: 'fa fa-close'
            }
          }
        );
  datepicker.css({
    width: '10rem'
  });
</script>

app/views/expenses/editWorkaround.html.erb
    <ul>
    <%= form_with model: @expense, url: expense_path(@expense), method: :patch, local: true do |f| %>
      <li><%= f.text_field :name %></li>
      <li><%= f.text_field :amount, data: {prefix:"$", thousands: ",", precision: 0}%></li>
      <li> 
        <div style="position: relative">
          <!-- this shit flies away -->
          <%= f.text_field :start, class: "datepicker" %>    
        </div> 
      </li>
      <li>
        <%=
          select_tag(
            :category_id,
            options_from_collection_for_select(@categories.order(:name), :id, :name, @expense.category_id)
          )
        %>
      </li>
      <li><%= f.check_box :owner, {checked: false} %> check to take the expense</li>
      <li><%= f.submit "Editar", class: "btn btn-success" %></li>
      <li><%= link_to "Back", expenses_sheet_url(@expense.expensesSheet), class: "btn btn-primary" %></li>
    <% end %>
    <ul>